#!/usr/bin/env bash

set -ex

## Build
BASE_PATH=`pwd`

version=${GIT_COMMIT}

make docker_base

docker build -t vitess/slim:latest -f square/Dockerfile.slim .

# Login to production AWS to publish new image
export REPO=system-utilities
export AWS_ROLE=cash-admin
export AWS_ACCOUNT_ID=912375853625
export SECRET=${SECRETS_PATH}/kochiku-worker-cash-aws-production.yaml
export AWS_REGION=us-east-1
export AWS_ACCESS_KEY_ID=$(ruby -ryaml -e "puts YAML.load_file(ENV['SECRET'])['aws_access_key_id']")
set +x
export AWS_SECRET_ACCESS_KEY=$(ruby -ryaml -e "puts YAML.load_file(ENV['SECRET'])['aws_secret_access_key']")
$(aws ecr get-login --no-include-email --region $AWS_REGION)
set -x

# Publish new image
remote_image=${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${REPO}:vitess-${version}
if [[ $(aws ecr describe-repositories --registry-id $AWS_ACCOUNT_ID --repository-names ${REPO} --region $AWS_REGION) ]]; then
  docker tag vitess/slim:latest ${remote_image}
  docker push ${remote_image}
else
  echo "Could not describe repository ${REPO} for AWS account ${AWS_ACCOUNT_ID} in region ${AWS_REGION}"
fi
