#!/usr/bin/env bash

set -ex

## Build
export REPO=vitess
export TAG=${GIT_COMMIT}

make docker_base

docker build -t $REPO:$TAG -f square/Dockerfile.slim .

CASH_CI_DIR=/tmp/cash-ci
rm -rf $CASH_CI_DIR
git clone ssh://git@git.sqcorp.co/cash/cash-ci.git $CASH_CI_DIR
$CASH_CI_DIR/cash-docker-push -r $REPO -t $TAG -p

