#!/usr/bin/env bash
set -euxo pipefail

# builds the square vitess docker image from the pwd and pushes a runnable image to ECR
# assumes GIT_COMMIT and GIT_BRANCH are set (which is true if run on kochiku)

# First we build using the regular vitess Dockerfile
BUILD_DOCKER_TAG=square-vitess-build-${GIT_COMMIT}
docker build -t "$BUILD_DOCKER_TAG" --build-arg CGO_ENABLED=0 .

REPO=square-vitess
TAG=${GIT_COMMIT}

# Now we build the vitess image we intend on running
# The underlying Dockerfile should be using an image tagged with $BUILD_DOCKER_TAG
# This is done so we can continue to use the normal vitess Dockerfile in the above build.
docker build -t "$REPO:$TAG" --build-arg GIT_COMMIT="${GIT_COMMIT}" --file square/Dockerfile .


if [[ "$GIT_BRANCH" != "master"  && -z "${KOCHIKU_CANARY_BUILD:-}" ]]; then
  echo "Git branch is not master or canary, not pushing image."
  exit 0
fi

CASH_CI_DIR=/tmp/cash-ci
rm -rf $CASH_CI_DIR
git clone ssh://git@git.sqcorp.co/cash/cash-ci.git $CASH_CI_DIR
$CASH_CI_DIR/cash-docker-push -r $REPO -t $TAG -p
