// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tabletmanagerdata.proto

/*
Package tabletmanagerdata is a generated protocol buffer package.

It is generated from these files:
	tabletmanagerdata.proto

It has these top-level messages:
	TableDefinition
	SchemaDefinition
	SchemaChangeResult
	UserPermission
	DbPermission
	Permissions
	BlpPosition
	PingRequest
	PingResponse
	SleepRequest
	SleepResponse
	ExecuteHookRequest
	ExecuteHookResponse
	GetSchemaRequest
	GetSchemaResponse
	GetPermissionsRequest
	GetPermissionsResponse
	SetReadOnlyRequest
	SetReadOnlyResponse
	SetReadWriteRequest
	SetReadWriteResponse
	ChangeTypeRequest
	ChangeTypeResponse
	RefreshStateRequest
	RefreshStateResponse
	RunHealthCheckRequest
	RunHealthCheckResponse
	IgnoreHealthErrorRequest
	IgnoreHealthErrorResponse
	ReloadSchemaRequest
	ReloadSchemaResponse
	PreflightSchemaRequest
	PreflightSchemaResponse
	ApplySchemaRequest
	ApplySchemaResponse
	ExecuteFetchAsDbaRequest
	ExecuteFetchAsDbaResponse
	ExecuteFetchAsAllPrivsRequest
	ExecuteFetchAsAllPrivsResponse
	ExecuteFetchAsAppRequest
	ExecuteFetchAsAppResponse
	SlaveStatusRequest
	SlaveStatusResponse
	MasterPositionRequest
	MasterPositionResponse
	StopSlaveRequest
	StopSlaveResponse
	StopSlaveMinimumRequest
	StopSlaveMinimumResponse
	StartSlaveRequest
	StartSlaveResponse
	TabletExternallyReparentedRequest
	TabletExternallyReparentedResponse
	TabletExternallyElectedRequest
	TabletExternallyElectedResponse
	GetSlavesRequest
	GetSlavesResponse
	WaitBlpPositionRequest
	WaitBlpPositionResponse
	StopBlpRequest
	StopBlpResponse
	StartBlpRequest
	StartBlpResponse
	RunBlpUntilRequest
	RunBlpUntilResponse
	ResetReplicationRequest
	ResetReplicationResponse
	InitMasterRequest
	InitMasterResponse
	PopulateReparentJournalRequest
	PopulateReparentJournalResponse
	InitSlaveRequest
	InitSlaveResponse
	DemoteMasterRequest
	DemoteMasterResponse
	PromoteSlaveWhenCaughtUpRequest
	PromoteSlaveWhenCaughtUpResponse
	SlaveWasPromotedRequest
	SlaveWasPromotedResponse
	SetMasterRequest
	SetMasterResponse
	SlaveWasRestartedRequest
	SlaveWasRestartedResponse
	StopReplicationAndGetStatusRequest
	StopReplicationAndGetStatusResponse
	PromoteSlaveRequest
	PromoteSlaveResponse
	BackupRequest
	BackupResponse
	RestoreFromBackupRequest
	RestoreFromBackupResponse
*/
package tabletmanagerdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import query "github.com/youtube/vitess/go/vt/proto/query"
import topodata "github.com/youtube/vitess/go/vt/proto/topodata"
import replicationdata "github.com/youtube/vitess/go/vt/proto/replicationdata"
import logutil "github.com/youtube/vitess/go/vt/proto/logutil"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TableDefinition struct {
	// the table name
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// the SQL to run to create the table
	Schema string `protobuf:"bytes,2,opt,name=schema" json:"schema,omitempty"`
	// the columns in the order that will be used to dump and load the data
	Columns []string `protobuf:"bytes,3,rep,name=columns" json:"columns,omitempty"`
	// the primary key columns in the primary key order
	PrimaryKeyColumns []string `protobuf:"bytes,4,rep,name=primary_key_columns,json=primaryKeyColumns" json:"primary_key_columns,omitempty"`
	// type is either mysqlctl.TableBaseTable or mysqlctl.TableView
	Type string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	// how much space the data file takes.
	DataLength uint64 `protobuf:"varint,6,opt,name=data_length,json=dataLength" json:"data_length,omitempty"`
	// approximate number of rows
	RowCount uint64 `protobuf:"varint,7,opt,name=row_count,json=rowCount" json:"row_count,omitempty"`
}

func (m *TableDefinition) Reset()                    { *m = TableDefinition{} }
func (m *TableDefinition) String() string            { return proto.CompactTextString(m) }
func (*TableDefinition) ProtoMessage()               {}
func (*TableDefinition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TableDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TableDefinition) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *TableDefinition) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *TableDefinition) GetPrimaryKeyColumns() []string {
	if m != nil {
		return m.PrimaryKeyColumns
	}
	return nil
}

func (m *TableDefinition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TableDefinition) GetDataLength() uint64 {
	if m != nil {
		return m.DataLength
	}
	return 0
}

func (m *TableDefinition) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

type SchemaDefinition struct {
	DatabaseSchema   string             `protobuf:"bytes,1,opt,name=database_schema,json=databaseSchema" json:"database_schema,omitempty"`
	TableDefinitions []*TableDefinition `protobuf:"bytes,2,rep,name=table_definitions,json=tableDefinitions" json:"table_definitions,omitempty"`
	Version          string             `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *SchemaDefinition) Reset()                    { *m = SchemaDefinition{} }
func (m *SchemaDefinition) String() string            { return proto.CompactTextString(m) }
func (*SchemaDefinition) ProtoMessage()               {}
func (*SchemaDefinition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SchemaDefinition) GetDatabaseSchema() string {
	if m != nil {
		return m.DatabaseSchema
	}
	return ""
}

func (m *SchemaDefinition) GetTableDefinitions() []*TableDefinition {
	if m != nil {
		return m.TableDefinitions
	}
	return nil
}

func (m *SchemaDefinition) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SchemaChangeResult struct {
	// before_schema holds the schema before each change.
	BeforeSchema *SchemaDefinition `protobuf:"bytes,1,opt,name=before_schema,json=beforeSchema" json:"before_schema,omitempty"`
	// after_schema holds the schema after each change.
	AfterSchema *SchemaDefinition `protobuf:"bytes,2,opt,name=after_schema,json=afterSchema" json:"after_schema,omitempty"`
}

func (m *SchemaChangeResult) Reset()                    { *m = SchemaChangeResult{} }
func (m *SchemaChangeResult) String() string            { return proto.CompactTextString(m) }
func (*SchemaChangeResult) ProtoMessage()               {}
func (*SchemaChangeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SchemaChangeResult) GetBeforeSchema() *SchemaDefinition {
	if m != nil {
		return m.BeforeSchema
	}
	return nil
}

func (m *SchemaChangeResult) GetAfterSchema() *SchemaDefinition {
	if m != nil {
		return m.AfterSchema
	}
	return nil
}

// UserPermission describes a single row in the mysql.user table
// Primary key is Host+User
// PasswordChecksum is the crc64 of the password, for security reasons
type UserPermission struct {
	Host             string            `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	User             string            `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	PasswordChecksum uint64            `protobuf:"varint,3,opt,name=password_checksum,json=passwordChecksum" json:"password_checksum,omitempty"`
	Privileges       map[string]string `protobuf:"bytes,4,rep,name=privileges" json:"privileges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *UserPermission) Reset()                    { *m = UserPermission{} }
func (m *UserPermission) String() string            { return proto.CompactTextString(m) }
func (*UserPermission) ProtoMessage()               {}
func (*UserPermission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserPermission) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *UserPermission) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UserPermission) GetPasswordChecksum() uint64 {
	if m != nil {
		return m.PasswordChecksum
	}
	return 0
}

func (m *UserPermission) GetPrivileges() map[string]string {
	if m != nil {
		return m.Privileges
	}
	return nil
}

// DbPermission describes a single row in the mysql.db table
// Primary key is Host+Db+User
type DbPermission struct {
	Host       string            `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Db         string            `protobuf:"bytes,2,opt,name=db" json:"db,omitempty"`
	User       string            `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Privileges map[string]string `protobuf:"bytes,4,rep,name=privileges" json:"privileges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *DbPermission) Reset()                    { *m = DbPermission{} }
func (m *DbPermission) String() string            { return proto.CompactTextString(m) }
func (*DbPermission) ProtoMessage()               {}
func (*DbPermission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DbPermission) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DbPermission) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *DbPermission) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *DbPermission) GetPrivileges() map[string]string {
	if m != nil {
		return m.Privileges
	}
	return nil
}

// Permissions have all the rows in mysql.{user,db} tables,
// (all rows are sorted by primary key)
type Permissions struct {
	UserPermissions []*UserPermission `protobuf:"bytes,1,rep,name=user_permissions,json=userPermissions" json:"user_permissions,omitempty"`
	DbPermissions   []*DbPermission   `protobuf:"bytes,2,rep,name=db_permissions,json=dbPermissions" json:"db_permissions,omitempty"`
}

func (m *Permissions) Reset()                    { *m = Permissions{} }
func (m *Permissions) String() string            { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()               {}
func (*Permissions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Permissions) GetUserPermissions() []*UserPermission {
	if m != nil {
		return m.UserPermissions
	}
	return nil
}

func (m *Permissions) GetDbPermissions() []*DbPermission {
	if m != nil {
		return m.DbPermissions
	}
	return nil
}

// BlpPosition is a replication position for a given binlog player
type BlpPosition struct {
	Uid      uint32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Position string `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
}

func (m *BlpPosition) Reset()                    { *m = BlpPosition{} }
func (m *BlpPosition) String() string            { return proto.CompactTextString(m) }
func (*BlpPosition) ProtoMessage()               {}
func (*BlpPosition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BlpPosition) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *BlpPosition) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type PingRequest struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PingRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type PingResponse struct {
	Payload string `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PingResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type SleepRequest struct {
	// duration is in nanoseconds
	Duration int64 `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
}

func (m *SleepRequest) Reset()                    { *m = SleepRequest{} }
func (m *SleepRequest) String() string            { return proto.CompactTextString(m) }
func (*SleepRequest) ProtoMessage()               {}
func (*SleepRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SleepRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type SleepResponse struct {
}

func (m *SleepResponse) Reset()                    { *m = SleepResponse{} }
func (m *SleepResponse) String() string            { return proto.CompactTextString(m) }
func (*SleepResponse) ProtoMessage()               {}
func (*SleepResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type ExecuteHookRequest struct {
	Name       string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Parameters []string          `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty"`
	ExtraEnv   map[string]string `protobuf:"bytes,3,rep,name=extra_env,json=extraEnv" json:"extra_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ExecuteHookRequest) Reset()                    { *m = ExecuteHookRequest{} }
func (m *ExecuteHookRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteHookRequest) ProtoMessage()               {}
func (*ExecuteHookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ExecuteHookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExecuteHookRequest) GetParameters() []string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ExecuteHookRequest) GetExtraEnv() map[string]string {
	if m != nil {
		return m.ExtraEnv
	}
	return nil
}

type ExecuteHookResponse struct {
	ExitStatus int64  `protobuf:"varint,1,opt,name=exit_status,json=exitStatus" json:"exit_status,omitempty"`
	Stdout     string `protobuf:"bytes,2,opt,name=stdout" json:"stdout,omitempty"`
	Stderr     string `protobuf:"bytes,3,opt,name=stderr" json:"stderr,omitempty"`
}

func (m *ExecuteHookResponse) Reset()                    { *m = ExecuteHookResponse{} }
func (m *ExecuteHookResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteHookResponse) ProtoMessage()               {}
func (*ExecuteHookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ExecuteHookResponse) GetExitStatus() int64 {
	if m != nil {
		return m.ExitStatus
	}
	return 0
}

func (m *ExecuteHookResponse) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *ExecuteHookResponse) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

type GetSchemaRequest struct {
	Tables        []string `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
	IncludeViews  bool     `protobuf:"varint,2,opt,name=include_views,json=includeViews" json:"include_views,omitempty"`
	ExcludeTables []string `protobuf:"bytes,3,rep,name=exclude_tables,json=excludeTables" json:"exclude_tables,omitempty"`
}

func (m *GetSchemaRequest) Reset()                    { *m = GetSchemaRequest{} }
func (m *GetSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSchemaRequest) ProtoMessage()               {}
func (*GetSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetSchemaRequest) GetTables() []string {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *GetSchemaRequest) GetIncludeViews() bool {
	if m != nil {
		return m.IncludeViews
	}
	return false
}

func (m *GetSchemaRequest) GetExcludeTables() []string {
	if m != nil {
		return m.ExcludeTables
	}
	return nil
}

type GetSchemaResponse struct {
	SchemaDefinition *SchemaDefinition `protobuf:"bytes,1,opt,name=schema_definition,json=schemaDefinition" json:"schema_definition,omitempty"`
}

func (m *GetSchemaResponse) Reset()                    { *m = GetSchemaResponse{} }
func (m *GetSchemaResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSchemaResponse) ProtoMessage()               {}
func (*GetSchemaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetSchemaResponse) GetSchemaDefinition() *SchemaDefinition {
	if m != nil {
		return m.SchemaDefinition
	}
	return nil
}

type GetPermissionsRequest struct {
}

func (m *GetPermissionsRequest) Reset()                    { *m = GetPermissionsRequest{} }
func (m *GetPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPermissionsRequest) ProtoMessage()               {}
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type GetPermissionsResponse struct {
	Permissions *Permissions `protobuf:"bytes,1,opt,name=permissions" json:"permissions,omitempty"`
}

func (m *GetPermissionsResponse) Reset()                    { *m = GetPermissionsResponse{} }
func (m *GetPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPermissionsResponse) ProtoMessage()               {}
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetPermissionsResponse) GetPermissions() *Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type SetReadOnlyRequest struct {
}

func (m *SetReadOnlyRequest) Reset()                    { *m = SetReadOnlyRequest{} }
func (m *SetReadOnlyRequest) String() string            { return proto.CompactTextString(m) }
func (*SetReadOnlyRequest) ProtoMessage()               {}
func (*SetReadOnlyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type SetReadOnlyResponse struct {
}

func (m *SetReadOnlyResponse) Reset()                    { *m = SetReadOnlyResponse{} }
func (m *SetReadOnlyResponse) String() string            { return proto.CompactTextString(m) }
func (*SetReadOnlyResponse) ProtoMessage()               {}
func (*SetReadOnlyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type SetReadWriteRequest struct {
}

func (m *SetReadWriteRequest) Reset()                    { *m = SetReadWriteRequest{} }
func (m *SetReadWriteRequest) String() string            { return proto.CompactTextString(m) }
func (*SetReadWriteRequest) ProtoMessage()               {}
func (*SetReadWriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type SetReadWriteResponse struct {
}

func (m *SetReadWriteResponse) Reset()                    { *m = SetReadWriteResponse{} }
func (m *SetReadWriteResponse) String() string            { return proto.CompactTextString(m) }
func (*SetReadWriteResponse) ProtoMessage()               {}
func (*SetReadWriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type ChangeTypeRequest struct {
	TabletType topodata.TabletType `protobuf:"varint,1,opt,name=tablet_type,json=tabletType,enum=topodata.TabletType" json:"tablet_type,omitempty"`
}

func (m *ChangeTypeRequest) Reset()                    { *m = ChangeTypeRequest{} }
func (m *ChangeTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeTypeRequest) ProtoMessage()               {}
func (*ChangeTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ChangeTypeRequest) GetTabletType() topodata.TabletType {
	if m != nil {
		return m.TabletType
	}
	return topodata.TabletType_UNKNOWN
}

type ChangeTypeResponse struct {
}

func (m *ChangeTypeResponse) Reset()                    { *m = ChangeTypeResponse{} }
func (m *ChangeTypeResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangeTypeResponse) ProtoMessage()               {}
func (*ChangeTypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type RefreshStateRequest struct {
}

func (m *RefreshStateRequest) Reset()                    { *m = RefreshStateRequest{} }
func (m *RefreshStateRequest) String() string            { return proto.CompactTextString(m) }
func (*RefreshStateRequest) ProtoMessage()               {}
func (*RefreshStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type RefreshStateResponse struct {
}

func (m *RefreshStateResponse) Reset()                    { *m = RefreshStateResponse{} }
func (m *RefreshStateResponse) String() string            { return proto.CompactTextString(m) }
func (*RefreshStateResponse) ProtoMessage()               {}
func (*RefreshStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type RunHealthCheckRequest struct {
}

func (m *RunHealthCheckRequest) Reset()                    { *m = RunHealthCheckRequest{} }
func (m *RunHealthCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*RunHealthCheckRequest) ProtoMessage()               {}
func (*RunHealthCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type RunHealthCheckResponse struct {
}

func (m *RunHealthCheckResponse) Reset()                    { *m = RunHealthCheckResponse{} }
func (m *RunHealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*RunHealthCheckResponse) ProtoMessage()               {}
func (*RunHealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type IgnoreHealthErrorRequest struct {
	Pattern string `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
}

func (m *IgnoreHealthErrorRequest) Reset()                    { *m = IgnoreHealthErrorRequest{} }
func (m *IgnoreHealthErrorRequest) String() string            { return proto.CompactTextString(m) }
func (*IgnoreHealthErrorRequest) ProtoMessage()               {}
func (*IgnoreHealthErrorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *IgnoreHealthErrorRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type IgnoreHealthErrorResponse struct {
}

func (m *IgnoreHealthErrorResponse) Reset()                    { *m = IgnoreHealthErrorResponse{} }
func (m *IgnoreHealthErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*IgnoreHealthErrorResponse) ProtoMessage()               {}
func (*IgnoreHealthErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type ReloadSchemaRequest struct {
	// wait_position allows scheduling a schema reload to occur after a
	// given DDL has replicated to this slave, by specifying a replication
	// position to wait for. Leave empty to trigger the reload immediately.
	WaitPosition string `protobuf:"bytes,1,opt,name=wait_position,json=waitPosition" json:"wait_position,omitempty"`
}

func (m *ReloadSchemaRequest) Reset()                    { *m = ReloadSchemaRequest{} }
func (m *ReloadSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*ReloadSchemaRequest) ProtoMessage()               {}
func (*ReloadSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ReloadSchemaRequest) GetWaitPosition() string {
	if m != nil {
		return m.WaitPosition
	}
	return ""
}

type ReloadSchemaResponse struct {
}

func (m *ReloadSchemaResponse) Reset()                    { *m = ReloadSchemaResponse{} }
func (m *ReloadSchemaResponse) String() string            { return proto.CompactTextString(m) }
func (*ReloadSchemaResponse) ProtoMessage()               {}
func (*ReloadSchemaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

type PreflightSchemaRequest struct {
	Changes []string `protobuf:"bytes,1,rep,name=changes" json:"changes,omitempty"`
}

func (m *PreflightSchemaRequest) Reset()                    { *m = PreflightSchemaRequest{} }
func (m *PreflightSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*PreflightSchemaRequest) ProtoMessage()               {}
func (*PreflightSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PreflightSchemaRequest) GetChanges() []string {
	if m != nil {
		return m.Changes
	}
	return nil
}

type PreflightSchemaResponse struct {
	// change_results has for each change the schema before and after it.
	// The number of elements is identical to the length of "changes" in the request.
	ChangeResults []*SchemaChangeResult `protobuf:"bytes,1,rep,name=change_results,json=changeResults" json:"change_results,omitempty"`
}

func (m *PreflightSchemaResponse) Reset()                    { *m = PreflightSchemaResponse{} }
func (m *PreflightSchemaResponse) String() string            { return proto.CompactTextString(m) }
func (*PreflightSchemaResponse) ProtoMessage()               {}
func (*PreflightSchemaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PreflightSchemaResponse) GetChangeResults() []*SchemaChangeResult {
	if m != nil {
		return m.ChangeResults
	}
	return nil
}

type ApplySchemaRequest struct {
	Sql              string            `protobuf:"bytes,1,opt,name=sql" json:"sql,omitempty"`
	Force            bool              `protobuf:"varint,2,opt,name=force" json:"force,omitempty"`
	AllowReplication bool              `protobuf:"varint,3,opt,name=allow_replication,json=allowReplication" json:"allow_replication,omitempty"`
	BeforeSchema     *SchemaDefinition `protobuf:"bytes,4,opt,name=before_schema,json=beforeSchema" json:"before_schema,omitempty"`
	AfterSchema      *SchemaDefinition `protobuf:"bytes,5,opt,name=after_schema,json=afterSchema" json:"after_schema,omitempty"`
}

func (m *ApplySchemaRequest) Reset()                    { *m = ApplySchemaRequest{} }
func (m *ApplySchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*ApplySchemaRequest) ProtoMessage()               {}
func (*ApplySchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *ApplySchemaRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *ApplySchemaRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *ApplySchemaRequest) GetAllowReplication() bool {
	if m != nil {
		return m.AllowReplication
	}
	return false
}

func (m *ApplySchemaRequest) GetBeforeSchema() *SchemaDefinition {
	if m != nil {
		return m.BeforeSchema
	}
	return nil
}

func (m *ApplySchemaRequest) GetAfterSchema() *SchemaDefinition {
	if m != nil {
		return m.AfterSchema
	}
	return nil
}

type ApplySchemaResponse struct {
	BeforeSchema *SchemaDefinition `protobuf:"bytes,1,opt,name=before_schema,json=beforeSchema" json:"before_schema,omitempty"`
	AfterSchema  *SchemaDefinition `protobuf:"bytes,2,opt,name=after_schema,json=afterSchema" json:"after_schema,omitempty"`
}

func (m *ApplySchemaResponse) Reset()                    { *m = ApplySchemaResponse{} }
func (m *ApplySchemaResponse) String() string            { return proto.CompactTextString(m) }
func (*ApplySchemaResponse) ProtoMessage()               {}
func (*ApplySchemaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *ApplySchemaResponse) GetBeforeSchema() *SchemaDefinition {
	if m != nil {
		return m.BeforeSchema
	}
	return nil
}

func (m *ApplySchemaResponse) GetAfterSchema() *SchemaDefinition {
	if m != nil {
		return m.AfterSchema
	}
	return nil
}

type ExecuteFetchAsDbaRequest struct {
	Query          []byte `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	DbName         string `protobuf:"bytes,2,opt,name=db_name,json=dbName" json:"db_name,omitempty"`
	MaxRows        uint64 `protobuf:"varint,3,opt,name=max_rows,json=maxRows" json:"max_rows,omitempty"`
	DisableBinlogs bool   `protobuf:"varint,4,opt,name=disable_binlogs,json=disableBinlogs" json:"disable_binlogs,omitempty"`
	ReloadSchema   bool   `protobuf:"varint,5,opt,name=reload_schema,json=reloadSchema" json:"reload_schema,omitempty"`
}

func (m *ExecuteFetchAsDbaRequest) Reset()                    { *m = ExecuteFetchAsDbaRequest{} }
func (m *ExecuteFetchAsDbaRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFetchAsDbaRequest) ProtoMessage()               {}
func (*ExecuteFetchAsDbaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *ExecuteFetchAsDbaRequest) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *ExecuteFetchAsDbaRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ExecuteFetchAsDbaRequest) GetMaxRows() uint64 {
	if m != nil {
		return m.MaxRows
	}
	return 0
}

func (m *ExecuteFetchAsDbaRequest) GetDisableBinlogs() bool {
	if m != nil {
		return m.DisableBinlogs
	}
	return false
}

func (m *ExecuteFetchAsDbaRequest) GetReloadSchema() bool {
	if m != nil {
		return m.ReloadSchema
	}
	return false
}

type ExecuteFetchAsDbaResponse struct {
	Result *query.QueryResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ExecuteFetchAsDbaResponse) Reset()                    { *m = ExecuteFetchAsDbaResponse{} }
func (m *ExecuteFetchAsDbaResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFetchAsDbaResponse) ProtoMessage()               {}
func (*ExecuteFetchAsDbaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *ExecuteFetchAsDbaResponse) GetResult() *query.QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ExecuteFetchAsAllPrivsRequest struct {
	Query        []byte `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	DbName       string `protobuf:"bytes,2,opt,name=db_name,json=dbName" json:"db_name,omitempty"`
	MaxRows      uint64 `protobuf:"varint,3,opt,name=max_rows,json=maxRows" json:"max_rows,omitempty"`
	ReloadSchema bool   `protobuf:"varint,4,opt,name=reload_schema,json=reloadSchema" json:"reload_schema,omitempty"`
}

func (m *ExecuteFetchAsAllPrivsRequest) Reset()                    { *m = ExecuteFetchAsAllPrivsRequest{} }
func (m *ExecuteFetchAsAllPrivsRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFetchAsAllPrivsRequest) ProtoMessage()               {}
func (*ExecuteFetchAsAllPrivsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *ExecuteFetchAsAllPrivsRequest) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *ExecuteFetchAsAllPrivsRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *ExecuteFetchAsAllPrivsRequest) GetMaxRows() uint64 {
	if m != nil {
		return m.MaxRows
	}
	return 0
}

func (m *ExecuteFetchAsAllPrivsRequest) GetReloadSchema() bool {
	if m != nil {
		return m.ReloadSchema
	}
	return false
}

type ExecuteFetchAsAllPrivsResponse struct {
	Result *query.QueryResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ExecuteFetchAsAllPrivsResponse) Reset()                    { *m = ExecuteFetchAsAllPrivsResponse{} }
func (m *ExecuteFetchAsAllPrivsResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFetchAsAllPrivsResponse) ProtoMessage()               {}
func (*ExecuteFetchAsAllPrivsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *ExecuteFetchAsAllPrivsResponse) GetResult() *query.QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ExecuteFetchAsAppRequest struct {
	Query   []byte `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MaxRows uint64 `protobuf:"varint,2,opt,name=max_rows,json=maxRows" json:"max_rows,omitempty"`
}

func (m *ExecuteFetchAsAppRequest) Reset()                    { *m = ExecuteFetchAsAppRequest{} }
func (m *ExecuteFetchAsAppRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFetchAsAppRequest) ProtoMessage()               {}
func (*ExecuteFetchAsAppRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *ExecuteFetchAsAppRequest) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *ExecuteFetchAsAppRequest) GetMaxRows() uint64 {
	if m != nil {
		return m.MaxRows
	}
	return 0
}

type ExecuteFetchAsAppResponse struct {
	Result *query.QueryResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ExecuteFetchAsAppResponse) Reset()                    { *m = ExecuteFetchAsAppResponse{} }
func (m *ExecuteFetchAsAppResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteFetchAsAppResponse) ProtoMessage()               {}
func (*ExecuteFetchAsAppResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *ExecuteFetchAsAppResponse) GetResult() *query.QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type SlaveStatusRequest struct {
}

func (m *SlaveStatusRequest) Reset()                    { *m = SlaveStatusRequest{} }
func (m *SlaveStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveStatusRequest) ProtoMessage()               {}
func (*SlaveStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

type SlaveStatusResponse struct {
	Status *replicationdata.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *SlaveStatusResponse) Reset()                    { *m = SlaveStatusResponse{} }
func (m *SlaveStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*SlaveStatusResponse) ProtoMessage()               {}
func (*SlaveStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *SlaveStatusResponse) GetStatus() *replicationdata.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type MasterPositionRequest struct {
}

func (m *MasterPositionRequest) Reset()                    { *m = MasterPositionRequest{} }
func (m *MasterPositionRequest) String() string            { return proto.CompactTextString(m) }
func (*MasterPositionRequest) ProtoMessage()               {}
func (*MasterPositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

type MasterPositionResponse struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *MasterPositionResponse) Reset()                    { *m = MasterPositionResponse{} }
func (m *MasterPositionResponse) String() string            { return proto.CompactTextString(m) }
func (*MasterPositionResponse) ProtoMessage()               {}
func (*MasterPositionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *MasterPositionResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type StopSlaveRequest struct {
}

func (m *StopSlaveRequest) Reset()                    { *m = StopSlaveRequest{} }
func (m *StopSlaveRequest) String() string            { return proto.CompactTextString(m) }
func (*StopSlaveRequest) ProtoMessage()               {}
func (*StopSlaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

type StopSlaveResponse struct {
}

func (m *StopSlaveResponse) Reset()                    { *m = StopSlaveResponse{} }
func (m *StopSlaveResponse) String() string            { return proto.CompactTextString(m) }
func (*StopSlaveResponse) ProtoMessage()               {}
func (*StopSlaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

type StopSlaveMinimumRequest struct {
	Position    string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	WaitTimeout int64  `protobuf:"varint,2,opt,name=wait_timeout,json=waitTimeout" json:"wait_timeout,omitempty"`
}

func (m *StopSlaveMinimumRequest) Reset()                    { *m = StopSlaveMinimumRequest{} }
func (m *StopSlaveMinimumRequest) String() string            { return proto.CompactTextString(m) }
func (*StopSlaveMinimumRequest) ProtoMessage()               {}
func (*StopSlaveMinimumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *StopSlaveMinimumRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *StopSlaveMinimumRequest) GetWaitTimeout() int64 {
	if m != nil {
		return m.WaitTimeout
	}
	return 0
}

type StopSlaveMinimumResponse struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *StopSlaveMinimumResponse) Reset()                    { *m = StopSlaveMinimumResponse{} }
func (m *StopSlaveMinimumResponse) String() string            { return proto.CompactTextString(m) }
func (*StopSlaveMinimumResponse) ProtoMessage()               {}
func (*StopSlaveMinimumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *StopSlaveMinimumResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type StartSlaveRequest struct {
}

func (m *StartSlaveRequest) Reset()                    { *m = StartSlaveRequest{} }
func (m *StartSlaveRequest) String() string            { return proto.CompactTextString(m) }
func (*StartSlaveRequest) ProtoMessage()               {}
func (*StartSlaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

type StartSlaveResponse struct {
}

func (m *StartSlaveResponse) Reset()                    { *m = StartSlaveResponse{} }
func (m *StartSlaveResponse) String() string            { return proto.CompactTextString(m) }
func (*StartSlaveResponse) ProtoMessage()               {}
func (*StartSlaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

type TabletExternallyReparentedRequest struct {
	// external_id is an string value that may be provided by an external
	// agent for tracking purposes. The tablet will emit this string in
	// events triggered by TabletExternallyReparented, such as VitessReparent.
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId" json:"external_id,omitempty"`
}

func (m *TabletExternallyReparentedRequest) Reset()         { *m = TabletExternallyReparentedRequest{} }
func (m *TabletExternallyReparentedRequest) String() string { return proto.CompactTextString(m) }
func (*TabletExternallyReparentedRequest) ProtoMessage()    {}
func (*TabletExternallyReparentedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{51}
}

func (m *TabletExternallyReparentedRequest) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

type TabletExternallyReparentedResponse struct {
}

func (m *TabletExternallyReparentedResponse) Reset()         { *m = TabletExternallyReparentedResponse{} }
func (m *TabletExternallyReparentedResponse) String() string { return proto.CompactTextString(m) }
func (*TabletExternallyReparentedResponse) ProtoMessage()    {}
func (*TabletExternallyReparentedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{52}
}

type TabletExternallyElectedRequest struct {
}

func (m *TabletExternallyElectedRequest) Reset()                    { *m = TabletExternallyElectedRequest{} }
func (m *TabletExternallyElectedRequest) String() string            { return proto.CompactTextString(m) }
func (*TabletExternallyElectedRequest) ProtoMessage()               {}
func (*TabletExternallyElectedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

type TabletExternallyElectedResponse struct {
}

func (m *TabletExternallyElectedResponse) Reset()         { *m = TabletExternallyElectedResponse{} }
func (m *TabletExternallyElectedResponse) String() string { return proto.CompactTextString(m) }
func (*TabletExternallyElectedResponse) ProtoMessage()    {}
func (*TabletExternallyElectedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{54}
}

type GetSlavesRequest struct {
}

func (m *GetSlavesRequest) Reset()                    { *m = GetSlavesRequest{} }
func (m *GetSlavesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSlavesRequest) ProtoMessage()               {}
func (*GetSlavesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{55} }

type GetSlavesResponse struct {
	Addrs []string `protobuf:"bytes,1,rep,name=addrs" json:"addrs,omitempty"`
}

func (m *GetSlavesResponse) Reset()                    { *m = GetSlavesResponse{} }
func (m *GetSlavesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSlavesResponse) ProtoMessage()               {}
func (*GetSlavesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{56} }

func (m *GetSlavesResponse) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

type WaitBlpPositionRequest struct {
	BlpPosition *BlpPosition `protobuf:"bytes,1,opt,name=blp_position,json=blpPosition" json:"blp_position,omitempty"`
	WaitTimeout int64        `protobuf:"varint,2,opt,name=wait_timeout,json=waitTimeout" json:"wait_timeout,omitempty"`
}

func (m *WaitBlpPositionRequest) Reset()                    { *m = WaitBlpPositionRequest{} }
func (m *WaitBlpPositionRequest) String() string            { return proto.CompactTextString(m) }
func (*WaitBlpPositionRequest) ProtoMessage()               {}
func (*WaitBlpPositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{57} }

func (m *WaitBlpPositionRequest) GetBlpPosition() *BlpPosition {
	if m != nil {
		return m.BlpPosition
	}
	return nil
}

func (m *WaitBlpPositionRequest) GetWaitTimeout() int64 {
	if m != nil {
		return m.WaitTimeout
	}
	return 0
}

type WaitBlpPositionResponse struct {
}

func (m *WaitBlpPositionResponse) Reset()                    { *m = WaitBlpPositionResponse{} }
func (m *WaitBlpPositionResponse) String() string            { return proto.CompactTextString(m) }
func (*WaitBlpPositionResponse) ProtoMessage()               {}
func (*WaitBlpPositionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{58} }

type StopBlpRequest struct {
}

func (m *StopBlpRequest) Reset()                    { *m = StopBlpRequest{} }
func (m *StopBlpRequest) String() string            { return proto.CompactTextString(m) }
func (*StopBlpRequest) ProtoMessage()               {}
func (*StopBlpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{59} }

type StopBlpResponse struct {
	BlpPositions []*BlpPosition `protobuf:"bytes,1,rep,name=blp_positions,json=blpPositions" json:"blp_positions,omitempty"`
}

func (m *StopBlpResponse) Reset()                    { *m = StopBlpResponse{} }
func (m *StopBlpResponse) String() string            { return proto.CompactTextString(m) }
func (*StopBlpResponse) ProtoMessage()               {}
func (*StopBlpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{60} }

func (m *StopBlpResponse) GetBlpPositions() []*BlpPosition {
	if m != nil {
		return m.BlpPositions
	}
	return nil
}

type StartBlpRequest struct {
}

func (m *StartBlpRequest) Reset()                    { *m = StartBlpRequest{} }
func (m *StartBlpRequest) String() string            { return proto.CompactTextString(m) }
func (*StartBlpRequest) ProtoMessage()               {}
func (*StartBlpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{61} }

type StartBlpResponse struct {
}

func (m *StartBlpResponse) Reset()                    { *m = StartBlpResponse{} }
func (m *StartBlpResponse) String() string            { return proto.CompactTextString(m) }
func (*StartBlpResponse) ProtoMessage()               {}
func (*StartBlpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{62} }

type RunBlpUntilRequest struct {
	BlpPositions    []*BlpPosition `protobuf:"bytes,1,rep,name=blp_positions,json=blpPositions" json:"blp_positions,omitempty"`
	WaitTimeout     int64          `protobuf:"varint,2,opt,name=wait_timeout,json=waitTimeout" json:"wait_timeout,omitempty"`
	IgnoreServerIds string         `protobuf:"bytes,3,opt,name=ignore_server_ids,json=ignoreServerIds" json:"ignore_server_ids,omitempty"`
}

func (m *RunBlpUntilRequest) Reset()                    { *m = RunBlpUntilRequest{} }
func (m *RunBlpUntilRequest) String() string            { return proto.CompactTextString(m) }
func (*RunBlpUntilRequest) ProtoMessage()               {}
func (*RunBlpUntilRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{63} }

func (m *RunBlpUntilRequest) GetBlpPositions() []*BlpPosition {
	if m != nil {
		return m.BlpPositions
	}
	return nil
}

func (m *RunBlpUntilRequest) GetWaitTimeout() int64 {
	if m != nil {
		return m.WaitTimeout
	}
	return 0
}

func (m *RunBlpUntilRequest) GetIgnoreServerIds() string {
	if m != nil {
		return m.IgnoreServerIds
	}
	return ""
}

type RunBlpUntilResponse struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *RunBlpUntilResponse) Reset()                    { *m = RunBlpUntilResponse{} }
func (m *RunBlpUntilResponse) String() string            { return proto.CompactTextString(m) }
func (*RunBlpUntilResponse) ProtoMessage()               {}
func (*RunBlpUntilResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{64} }

func (m *RunBlpUntilResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type ResetReplicationRequest struct {
}

func (m *ResetReplicationRequest) Reset()                    { *m = ResetReplicationRequest{} }
func (m *ResetReplicationRequest) String() string            { return proto.CompactTextString(m) }
func (*ResetReplicationRequest) ProtoMessage()               {}
func (*ResetReplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{65} }

type ResetReplicationResponse struct {
}

func (m *ResetReplicationResponse) Reset()                    { *m = ResetReplicationResponse{} }
func (m *ResetReplicationResponse) String() string            { return proto.CompactTextString(m) }
func (*ResetReplicationResponse) ProtoMessage()               {}
func (*ResetReplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{66} }

type InitMasterRequest struct {
}

func (m *InitMasterRequest) Reset()                    { *m = InitMasterRequest{} }
func (m *InitMasterRequest) String() string            { return proto.CompactTextString(m) }
func (*InitMasterRequest) ProtoMessage()               {}
func (*InitMasterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{67} }

type InitMasterResponse struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *InitMasterResponse) Reset()                    { *m = InitMasterResponse{} }
func (m *InitMasterResponse) String() string            { return proto.CompactTextString(m) }
func (*InitMasterResponse) ProtoMessage()               {}
func (*InitMasterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{68} }

func (m *InitMasterResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type PopulateReparentJournalRequest struct {
	TimeCreatedNs       int64                 `protobuf:"varint,1,opt,name=time_created_ns,json=timeCreatedNs" json:"time_created_ns,omitempty"`
	ActionName          string                `protobuf:"bytes,2,opt,name=action_name,json=actionName" json:"action_name,omitempty"`
	MasterAlias         *topodata.TabletAlias `protobuf:"bytes,3,opt,name=master_alias,json=masterAlias" json:"master_alias,omitempty"`
	ReplicationPosition string                `protobuf:"bytes,4,opt,name=replication_position,json=replicationPosition" json:"replication_position,omitempty"`
}

func (m *PopulateReparentJournalRequest) Reset()                    { *m = PopulateReparentJournalRequest{} }
func (m *PopulateReparentJournalRequest) String() string            { return proto.CompactTextString(m) }
func (*PopulateReparentJournalRequest) ProtoMessage()               {}
func (*PopulateReparentJournalRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{69} }

func (m *PopulateReparentJournalRequest) GetTimeCreatedNs() int64 {
	if m != nil {
		return m.TimeCreatedNs
	}
	return 0
}

func (m *PopulateReparentJournalRequest) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *PopulateReparentJournalRequest) GetMasterAlias() *topodata.TabletAlias {
	if m != nil {
		return m.MasterAlias
	}
	return nil
}

func (m *PopulateReparentJournalRequest) GetReplicationPosition() string {
	if m != nil {
		return m.ReplicationPosition
	}
	return ""
}

type PopulateReparentJournalResponse struct {
}

func (m *PopulateReparentJournalResponse) Reset()         { *m = PopulateReparentJournalResponse{} }
func (m *PopulateReparentJournalResponse) String() string { return proto.CompactTextString(m) }
func (*PopulateReparentJournalResponse) ProtoMessage()    {}
func (*PopulateReparentJournalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{70}
}

type InitSlaveRequest struct {
	Parent              *topodata.TabletAlias `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	ReplicationPosition string                `protobuf:"bytes,2,opt,name=replication_position,json=replicationPosition" json:"replication_position,omitempty"`
	TimeCreatedNs       int64                 `protobuf:"varint,3,opt,name=time_created_ns,json=timeCreatedNs" json:"time_created_ns,omitempty"`
}

func (m *InitSlaveRequest) Reset()                    { *m = InitSlaveRequest{} }
func (m *InitSlaveRequest) String() string            { return proto.CompactTextString(m) }
func (*InitSlaveRequest) ProtoMessage()               {}
func (*InitSlaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{71} }

func (m *InitSlaveRequest) GetParent() *topodata.TabletAlias {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *InitSlaveRequest) GetReplicationPosition() string {
	if m != nil {
		return m.ReplicationPosition
	}
	return ""
}

func (m *InitSlaveRequest) GetTimeCreatedNs() int64 {
	if m != nil {
		return m.TimeCreatedNs
	}
	return 0
}

type InitSlaveResponse struct {
}

func (m *InitSlaveResponse) Reset()                    { *m = InitSlaveResponse{} }
func (m *InitSlaveResponse) String() string            { return proto.CompactTextString(m) }
func (*InitSlaveResponse) ProtoMessage()               {}
func (*InitSlaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{72} }

type DemoteMasterRequest struct {
}

func (m *DemoteMasterRequest) Reset()                    { *m = DemoteMasterRequest{} }
func (m *DemoteMasterRequest) String() string            { return proto.CompactTextString(m) }
func (*DemoteMasterRequest) ProtoMessage()               {}
func (*DemoteMasterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{73} }

type DemoteMasterResponse struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *DemoteMasterResponse) Reset()                    { *m = DemoteMasterResponse{} }
func (m *DemoteMasterResponse) String() string            { return proto.CompactTextString(m) }
func (*DemoteMasterResponse) ProtoMessage()               {}
func (*DemoteMasterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{74} }

func (m *DemoteMasterResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type PromoteSlaveWhenCaughtUpRequest struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *PromoteSlaveWhenCaughtUpRequest) Reset()         { *m = PromoteSlaveWhenCaughtUpRequest{} }
func (m *PromoteSlaveWhenCaughtUpRequest) String() string { return proto.CompactTextString(m) }
func (*PromoteSlaveWhenCaughtUpRequest) ProtoMessage()    {}
func (*PromoteSlaveWhenCaughtUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{75}
}

func (m *PromoteSlaveWhenCaughtUpRequest) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type PromoteSlaveWhenCaughtUpResponse struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *PromoteSlaveWhenCaughtUpResponse) Reset()         { *m = PromoteSlaveWhenCaughtUpResponse{} }
func (m *PromoteSlaveWhenCaughtUpResponse) String() string { return proto.CompactTextString(m) }
func (*PromoteSlaveWhenCaughtUpResponse) ProtoMessage()    {}
func (*PromoteSlaveWhenCaughtUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{76}
}

func (m *PromoteSlaveWhenCaughtUpResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type SlaveWasPromotedRequest struct {
}

func (m *SlaveWasPromotedRequest) Reset()                    { *m = SlaveWasPromotedRequest{} }
func (m *SlaveWasPromotedRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveWasPromotedRequest) ProtoMessage()               {}
func (*SlaveWasPromotedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{77} }

type SlaveWasPromotedResponse struct {
}

func (m *SlaveWasPromotedResponse) Reset()                    { *m = SlaveWasPromotedResponse{} }
func (m *SlaveWasPromotedResponse) String() string            { return proto.CompactTextString(m) }
func (*SlaveWasPromotedResponse) ProtoMessage()               {}
func (*SlaveWasPromotedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{78} }

type SetMasterRequest struct {
	Parent          *topodata.TabletAlias `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	TimeCreatedNs   int64                 `protobuf:"varint,2,opt,name=time_created_ns,json=timeCreatedNs" json:"time_created_ns,omitempty"`
	ForceStartSlave bool                  `protobuf:"varint,3,opt,name=force_start_slave,json=forceStartSlave" json:"force_start_slave,omitempty"`
}

func (m *SetMasterRequest) Reset()                    { *m = SetMasterRequest{} }
func (m *SetMasterRequest) String() string            { return proto.CompactTextString(m) }
func (*SetMasterRequest) ProtoMessage()               {}
func (*SetMasterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{79} }

func (m *SetMasterRequest) GetParent() *topodata.TabletAlias {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *SetMasterRequest) GetTimeCreatedNs() int64 {
	if m != nil {
		return m.TimeCreatedNs
	}
	return 0
}

func (m *SetMasterRequest) GetForceStartSlave() bool {
	if m != nil {
		return m.ForceStartSlave
	}
	return false
}

type SetMasterResponse struct {
}

func (m *SetMasterResponse) Reset()                    { *m = SetMasterResponse{} }
func (m *SetMasterResponse) String() string            { return proto.CompactTextString(m) }
func (*SetMasterResponse) ProtoMessage()               {}
func (*SetMasterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{80} }

type SlaveWasRestartedRequest struct {
	// the parent alias the tablet should have
	Parent *topodata.TabletAlias `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
}

func (m *SlaveWasRestartedRequest) Reset()                    { *m = SlaveWasRestartedRequest{} }
func (m *SlaveWasRestartedRequest) String() string            { return proto.CompactTextString(m) }
func (*SlaveWasRestartedRequest) ProtoMessage()               {}
func (*SlaveWasRestartedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{81} }

func (m *SlaveWasRestartedRequest) GetParent() *topodata.TabletAlias {
	if m != nil {
		return m.Parent
	}
	return nil
}

type SlaveWasRestartedResponse struct {
}

func (m *SlaveWasRestartedResponse) Reset()                    { *m = SlaveWasRestartedResponse{} }
func (m *SlaveWasRestartedResponse) String() string            { return proto.CompactTextString(m) }
func (*SlaveWasRestartedResponse) ProtoMessage()               {}
func (*SlaveWasRestartedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{82} }

type StopReplicationAndGetStatusRequest struct {
}

func (m *StopReplicationAndGetStatusRequest) Reset()         { *m = StopReplicationAndGetStatusRequest{} }
func (m *StopReplicationAndGetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*StopReplicationAndGetStatusRequest) ProtoMessage()    {}
func (*StopReplicationAndGetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{83}
}

type StopReplicationAndGetStatusResponse struct {
	Status *replicationdata.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *StopReplicationAndGetStatusResponse) Reset()         { *m = StopReplicationAndGetStatusResponse{} }
func (m *StopReplicationAndGetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*StopReplicationAndGetStatusResponse) ProtoMessage()    {}
func (*StopReplicationAndGetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{84}
}

func (m *StopReplicationAndGetStatusResponse) GetStatus() *replicationdata.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type PromoteSlaveRequest struct {
}

func (m *PromoteSlaveRequest) Reset()                    { *m = PromoteSlaveRequest{} }
func (m *PromoteSlaveRequest) String() string            { return proto.CompactTextString(m) }
func (*PromoteSlaveRequest) ProtoMessage()               {}
func (*PromoteSlaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{85} }

type PromoteSlaveResponse struct {
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *PromoteSlaveResponse) Reset()                    { *m = PromoteSlaveResponse{} }
func (m *PromoteSlaveResponse) String() string            { return proto.CompactTextString(m) }
func (*PromoteSlaveResponse) ProtoMessage()               {}
func (*PromoteSlaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{86} }

func (m *PromoteSlaveResponse) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

type BackupRequest struct {
	Concurrency int64 `protobuf:"varint,1,opt,name=concurrency" json:"concurrency,omitempty"`
}

func (m *BackupRequest) Reset()                    { *m = BackupRequest{} }
func (m *BackupRequest) String() string            { return proto.CompactTextString(m) }
func (*BackupRequest) ProtoMessage()               {}
func (*BackupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{87} }

func (m *BackupRequest) GetConcurrency() int64 {
	if m != nil {
		return m.Concurrency
	}
	return 0
}

type BackupResponse struct {
	Event *logutil.Event `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
}

func (m *BackupResponse) Reset()                    { *m = BackupResponse{} }
func (m *BackupResponse) String() string            { return proto.CompactTextString(m) }
func (*BackupResponse) ProtoMessage()               {}
func (*BackupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{88} }

func (m *BackupResponse) GetEvent() *logutil.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type RestoreFromBackupRequest struct {
}

func (m *RestoreFromBackupRequest) Reset()                    { *m = RestoreFromBackupRequest{} }
func (m *RestoreFromBackupRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreFromBackupRequest) ProtoMessage()               {}
func (*RestoreFromBackupRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{89} }

type RestoreFromBackupResponse struct {
	Event *logutil.Event `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
}

func (m *RestoreFromBackupResponse) Reset()                    { *m = RestoreFromBackupResponse{} }
func (m *RestoreFromBackupResponse) String() string            { return proto.CompactTextString(m) }
func (*RestoreFromBackupResponse) ProtoMessage()               {}
func (*RestoreFromBackupResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{90} }

func (m *RestoreFromBackupResponse) GetEvent() *logutil.Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterType((*TableDefinition)(nil), "tabletmanagerdata.TableDefinition")
	proto.RegisterType((*SchemaDefinition)(nil), "tabletmanagerdata.SchemaDefinition")
	proto.RegisterType((*SchemaChangeResult)(nil), "tabletmanagerdata.SchemaChangeResult")
	proto.RegisterType((*UserPermission)(nil), "tabletmanagerdata.UserPermission")
	proto.RegisterType((*DbPermission)(nil), "tabletmanagerdata.DbPermission")
	proto.RegisterType((*Permissions)(nil), "tabletmanagerdata.Permissions")
	proto.RegisterType((*BlpPosition)(nil), "tabletmanagerdata.BlpPosition")
	proto.RegisterType((*PingRequest)(nil), "tabletmanagerdata.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "tabletmanagerdata.PingResponse")
	proto.RegisterType((*SleepRequest)(nil), "tabletmanagerdata.SleepRequest")
	proto.RegisterType((*SleepResponse)(nil), "tabletmanagerdata.SleepResponse")
	proto.RegisterType((*ExecuteHookRequest)(nil), "tabletmanagerdata.ExecuteHookRequest")
	proto.RegisterType((*ExecuteHookResponse)(nil), "tabletmanagerdata.ExecuteHookResponse")
	proto.RegisterType((*GetSchemaRequest)(nil), "tabletmanagerdata.GetSchemaRequest")
	proto.RegisterType((*GetSchemaResponse)(nil), "tabletmanagerdata.GetSchemaResponse")
	proto.RegisterType((*GetPermissionsRequest)(nil), "tabletmanagerdata.GetPermissionsRequest")
	proto.RegisterType((*GetPermissionsResponse)(nil), "tabletmanagerdata.GetPermissionsResponse")
	proto.RegisterType((*SetReadOnlyRequest)(nil), "tabletmanagerdata.SetReadOnlyRequest")
	proto.RegisterType((*SetReadOnlyResponse)(nil), "tabletmanagerdata.SetReadOnlyResponse")
	proto.RegisterType((*SetReadWriteRequest)(nil), "tabletmanagerdata.SetReadWriteRequest")
	proto.RegisterType((*SetReadWriteResponse)(nil), "tabletmanagerdata.SetReadWriteResponse")
	proto.RegisterType((*ChangeTypeRequest)(nil), "tabletmanagerdata.ChangeTypeRequest")
	proto.RegisterType((*ChangeTypeResponse)(nil), "tabletmanagerdata.ChangeTypeResponse")
	proto.RegisterType((*RefreshStateRequest)(nil), "tabletmanagerdata.RefreshStateRequest")
	proto.RegisterType((*RefreshStateResponse)(nil), "tabletmanagerdata.RefreshStateResponse")
	proto.RegisterType((*RunHealthCheckRequest)(nil), "tabletmanagerdata.RunHealthCheckRequest")
	proto.RegisterType((*RunHealthCheckResponse)(nil), "tabletmanagerdata.RunHealthCheckResponse")
	proto.RegisterType((*IgnoreHealthErrorRequest)(nil), "tabletmanagerdata.IgnoreHealthErrorRequest")
	proto.RegisterType((*IgnoreHealthErrorResponse)(nil), "tabletmanagerdata.IgnoreHealthErrorResponse")
	proto.RegisterType((*ReloadSchemaRequest)(nil), "tabletmanagerdata.ReloadSchemaRequest")
	proto.RegisterType((*ReloadSchemaResponse)(nil), "tabletmanagerdata.ReloadSchemaResponse")
	proto.RegisterType((*PreflightSchemaRequest)(nil), "tabletmanagerdata.PreflightSchemaRequest")
	proto.RegisterType((*PreflightSchemaResponse)(nil), "tabletmanagerdata.PreflightSchemaResponse")
	proto.RegisterType((*ApplySchemaRequest)(nil), "tabletmanagerdata.ApplySchemaRequest")
	proto.RegisterType((*ApplySchemaResponse)(nil), "tabletmanagerdata.ApplySchemaResponse")
	proto.RegisterType((*ExecuteFetchAsDbaRequest)(nil), "tabletmanagerdata.ExecuteFetchAsDbaRequest")
	proto.RegisterType((*ExecuteFetchAsDbaResponse)(nil), "tabletmanagerdata.ExecuteFetchAsDbaResponse")
	proto.RegisterType((*ExecuteFetchAsAllPrivsRequest)(nil), "tabletmanagerdata.ExecuteFetchAsAllPrivsRequest")
	proto.RegisterType((*ExecuteFetchAsAllPrivsResponse)(nil), "tabletmanagerdata.ExecuteFetchAsAllPrivsResponse")
	proto.RegisterType((*ExecuteFetchAsAppRequest)(nil), "tabletmanagerdata.ExecuteFetchAsAppRequest")
	proto.RegisterType((*ExecuteFetchAsAppResponse)(nil), "tabletmanagerdata.ExecuteFetchAsAppResponse")
	proto.RegisterType((*SlaveStatusRequest)(nil), "tabletmanagerdata.SlaveStatusRequest")
	proto.RegisterType((*SlaveStatusResponse)(nil), "tabletmanagerdata.SlaveStatusResponse")
	proto.RegisterType((*MasterPositionRequest)(nil), "tabletmanagerdata.MasterPositionRequest")
	proto.RegisterType((*MasterPositionResponse)(nil), "tabletmanagerdata.MasterPositionResponse")
	proto.RegisterType((*StopSlaveRequest)(nil), "tabletmanagerdata.StopSlaveRequest")
	proto.RegisterType((*StopSlaveResponse)(nil), "tabletmanagerdata.StopSlaveResponse")
	proto.RegisterType((*StopSlaveMinimumRequest)(nil), "tabletmanagerdata.StopSlaveMinimumRequest")
	proto.RegisterType((*StopSlaveMinimumResponse)(nil), "tabletmanagerdata.StopSlaveMinimumResponse")
	proto.RegisterType((*StartSlaveRequest)(nil), "tabletmanagerdata.StartSlaveRequest")
	proto.RegisterType((*StartSlaveResponse)(nil), "tabletmanagerdata.StartSlaveResponse")
	proto.RegisterType((*TabletExternallyReparentedRequest)(nil), "tabletmanagerdata.TabletExternallyReparentedRequest")
	proto.RegisterType((*TabletExternallyReparentedResponse)(nil), "tabletmanagerdata.TabletExternallyReparentedResponse")
	proto.RegisterType((*TabletExternallyElectedRequest)(nil), "tabletmanagerdata.TabletExternallyElectedRequest")
	proto.RegisterType((*TabletExternallyElectedResponse)(nil), "tabletmanagerdata.TabletExternallyElectedResponse")
	proto.RegisterType((*GetSlavesRequest)(nil), "tabletmanagerdata.GetSlavesRequest")
	proto.RegisterType((*GetSlavesResponse)(nil), "tabletmanagerdata.GetSlavesResponse")
	proto.RegisterType((*WaitBlpPositionRequest)(nil), "tabletmanagerdata.WaitBlpPositionRequest")
	proto.RegisterType((*WaitBlpPositionResponse)(nil), "tabletmanagerdata.WaitBlpPositionResponse")
	proto.RegisterType((*StopBlpRequest)(nil), "tabletmanagerdata.StopBlpRequest")
	proto.RegisterType((*StopBlpResponse)(nil), "tabletmanagerdata.StopBlpResponse")
	proto.RegisterType((*StartBlpRequest)(nil), "tabletmanagerdata.StartBlpRequest")
	proto.RegisterType((*StartBlpResponse)(nil), "tabletmanagerdata.StartBlpResponse")
	proto.RegisterType((*RunBlpUntilRequest)(nil), "tabletmanagerdata.RunBlpUntilRequest")
	proto.RegisterType((*RunBlpUntilResponse)(nil), "tabletmanagerdata.RunBlpUntilResponse")
	proto.RegisterType((*ResetReplicationRequest)(nil), "tabletmanagerdata.ResetReplicationRequest")
	proto.RegisterType((*ResetReplicationResponse)(nil), "tabletmanagerdata.ResetReplicationResponse")
	proto.RegisterType((*InitMasterRequest)(nil), "tabletmanagerdata.InitMasterRequest")
	proto.RegisterType((*InitMasterResponse)(nil), "tabletmanagerdata.InitMasterResponse")
	proto.RegisterType((*PopulateReparentJournalRequest)(nil), "tabletmanagerdata.PopulateReparentJournalRequest")
	proto.RegisterType((*PopulateReparentJournalResponse)(nil), "tabletmanagerdata.PopulateReparentJournalResponse")
	proto.RegisterType((*InitSlaveRequest)(nil), "tabletmanagerdata.InitSlaveRequest")
	proto.RegisterType((*InitSlaveResponse)(nil), "tabletmanagerdata.InitSlaveResponse")
	proto.RegisterType((*DemoteMasterRequest)(nil), "tabletmanagerdata.DemoteMasterRequest")
	proto.RegisterType((*DemoteMasterResponse)(nil), "tabletmanagerdata.DemoteMasterResponse")
	proto.RegisterType((*PromoteSlaveWhenCaughtUpRequest)(nil), "tabletmanagerdata.PromoteSlaveWhenCaughtUpRequest")
	proto.RegisterType((*PromoteSlaveWhenCaughtUpResponse)(nil), "tabletmanagerdata.PromoteSlaveWhenCaughtUpResponse")
	proto.RegisterType((*SlaveWasPromotedRequest)(nil), "tabletmanagerdata.SlaveWasPromotedRequest")
	proto.RegisterType((*SlaveWasPromotedResponse)(nil), "tabletmanagerdata.SlaveWasPromotedResponse")
	proto.RegisterType((*SetMasterRequest)(nil), "tabletmanagerdata.SetMasterRequest")
	proto.RegisterType((*SetMasterResponse)(nil), "tabletmanagerdata.SetMasterResponse")
	proto.RegisterType((*SlaveWasRestartedRequest)(nil), "tabletmanagerdata.SlaveWasRestartedRequest")
	proto.RegisterType((*SlaveWasRestartedResponse)(nil), "tabletmanagerdata.SlaveWasRestartedResponse")
	proto.RegisterType((*StopReplicationAndGetStatusRequest)(nil), "tabletmanagerdata.StopReplicationAndGetStatusRequest")
	proto.RegisterType((*StopReplicationAndGetStatusResponse)(nil), "tabletmanagerdata.StopReplicationAndGetStatusResponse")
	proto.RegisterType((*PromoteSlaveRequest)(nil), "tabletmanagerdata.PromoteSlaveRequest")
	proto.RegisterType((*PromoteSlaveResponse)(nil), "tabletmanagerdata.PromoteSlaveResponse")
	proto.RegisterType((*BackupRequest)(nil), "tabletmanagerdata.BackupRequest")
	proto.RegisterType((*BackupResponse)(nil), "tabletmanagerdata.BackupResponse")
	proto.RegisterType((*RestoreFromBackupRequest)(nil), "tabletmanagerdata.RestoreFromBackupRequest")
	proto.RegisterType((*RestoreFromBackupResponse)(nil), "tabletmanagerdata.RestoreFromBackupResponse")
}

func init() { proto.RegisterFile("tabletmanagerdata.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2074 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0x5b, 0x6f, 0x1b, 0xc7,
	0x15, 0xc6, 0x8a, 0x92, 0x2c, 0x9d, 0x25, 0x29, 0x72, 0xa9, 0x0b, 0xa5, 0xa0, 0xba, 0xac, 0x9d,
	0x46, 0x75, 0x51, 0xa5, 0x56, 0xd2, 0x20, 0x48, 0x90, 0xa2, 0xba, 0xda, 0x4a, 0x9c, 0x58, 0x59,
	0xf9, 0x52, 0xf4, 0x65, 0x31, 0xdc, 0x1d, 0x91, 0x0b, 0x2d, 0x77, 0xd7, 0x33, 0xb3, 0x94, 0xf8,
	0xd2, 0x9f, 0xd0, 0xb7, 0xbe, 0xf5, 0xad, 0x40, 0xdb, 0xe7, 0xfe, 0x18, 0x17, 0xfd, 0x25, 0x7d,
	0xe8, 0x4b, 0x31, 0x37, 0x72, 0x96, 0xa4, 0x6c, 0xca, 0x70, 0x81, 0xbc, 0x08, 0x9c, 0xef, 0xdc,
	0xcf, 0x9c, 0x39, 0xe7, 0x2c, 0x04, 0x6b, 0x0c, 0xb5, 0x62, 0xcc, 0xba, 0x28, 0x41, 0x6d, 0x4c,
	0x42, 0xc4, 0xd0, 0x5e, 0x46, 0x52, 0x96, 0x3a, 0xf5, 0x31, 0xc2, 0x86, 0xfd, 0x3a, 0xc7, 0xa4,
	0x2f, 0xe9, 0x1b, 0x55, 0x96, 0x66, 0xe9, 0x90, 0x7f, 0x63, 0x85, 0xe0, 0x2c, 0x8e, 0x02, 0xc4,
	0xa2, 0x34, 0x31, 0xe0, 0x4a, 0x9c, 0xb6, 0x73, 0x16, 0xc5, 0xf2, 0xe8, 0xfe, 0xdb, 0x82, 0xa5,
	0xe7, 0x5c, 0xf1, 0x31, 0xbe, 0x8c, 0x92, 0x88, 0x33, 0x3b, 0x0e, 0xcc, 0x26, 0xa8, 0x8b, 0x9b,
	0xd6, 0xb6, 0xb5, 0xbb, 0xe8, 0x89, 0xdf, 0xce, 0x2a, 0xcc, 0xd3, 0xa0, 0x83, 0xbb, 0xa8, 0x39,
	0x23, 0x50, 0x75, 0x72, 0x9a, 0x70, 0x2f, 0x48, 0xe3, 0xbc, 0x9b, 0xd0, 0x66, 0x69, 0xbb, 0xb4,
	0xbb, 0xe8, 0xe9, 0xa3, 0xb3, 0x07, 0x8d, 0x8c, 0x44, 0x5d, 0x44, 0xfa, 0xfe, 0x15, 0xee, 0xfb,
	0x9a, 0x6b, 0x56, 0x70, 0xd5, 0x15, 0xe9, 0x3b, 0xdc, 0x3f, 0x52, 0xfc, 0x0e, 0xcc, 0xb2, 0x7e,
	0x86, 0x9b, 0x73, 0xd2, 0x2a, 0xff, 0xed, 0x6c, 0x81, 0xcd, 0x5d, 0xf7, 0x63, 0x9c, 0xb4, 0x59,
	0xa7, 0x39, 0xbf, 0x6d, 0xed, 0xce, 0x7a, 0xc0, 0xa1, 0xa7, 0x02, 0x71, 0x3e, 0x82, 0x45, 0x92,
	0x5e, 0xfb, 0x41, 0x9a, 0x27, 0xac, 0x79, 0x4f, 0x90, 0x17, 0x48, 0x7a, 0x7d, 0xc4, 0xcf, 0xee,
	0xdf, 0x2c, 0xa8, 0x5d, 0x08, 0x37, 0x8d, 0xe0, 0x3e, 0x81, 0x25, 0x2e, 0xdf, 0x42, 0x14, 0xfb,
	0x2a, 0x22, 0x19, 0x67, 0x55, 0xc3, 0x52, 0xc4, 0x79, 0x06, 0x32, 0xe3, 0x7e, 0x38, 0x10, 0xa6,
	0xcd, 0x99, 0xed, 0xd2, 0xae, 0xbd, 0xef, 0xee, 0x8d, 0x5f, 0xd2, 0x48, 0x12, 0xbd, 0x1a, 0x2b,
	0x02, 0x94, 0xa7, 0xaa, 0x87, 0x09, 0x8d, 0xd2, 0xa4, 0x59, 0x12, 0x16, 0xf5, 0x91, 0x3b, 0xea,
	0x48, 0xab, 0x47, 0x1d, 0x94, 0xb4, 0xb1, 0x87, 0x69, 0x1e, 0x33, 0xe7, 0x09, 0x54, 0x5a, 0xf8,
	0x32, 0x25, 0x05, 0x47, 0xed, 0xfd, 0xfb, 0x13, 0xac, 0x8f, 0x86, 0xe9, 0x95, 0xa5, 0xa4, 0x8a,
	0xe5, 0x14, 0xca, 0xe8, 0x92, 0x61, 0xe2, 0x1b, 0x77, 0x38, 0xa5, 0x22, 0x5b, 0x08, 0x4a, 0xd8,
	0xfd, 0x8f, 0x05, 0xd5, 0x17, 0x14, 0x93, 0x73, 0x4c, 0xba, 0x11, 0xa5, 0xaa, 0x58, 0x3a, 0x29,
	0x65, 0xba, 0x58, 0xf8, 0x6f, 0x8e, 0xe5, 0x14, 0x13, 0x55, 0x2a, 0xe2, 0xb7, 0xf3, 0x4b, 0xa8,
	0x67, 0x88, 0xd2, 0xeb, 0x94, 0x84, 0x7e, 0xd0, 0xc1, 0xc1, 0x15, 0xcd, 0xbb, 0x22, 0x0f, 0xb3,
	0x5e, 0x4d, 0x13, 0x8e, 0x14, 0xee, 0xfc, 0x08, 0x90, 0x91, 0xa8, 0x17, 0xc5, 0xb8, 0x8d, 0x65,
	0xc9, 0xd8, 0xfb, 0x8f, 0x26, 0x78, 0x5b, 0xf4, 0x65, 0xef, 0x7c, 0x20, 0x73, 0x92, 0x30, 0xd2,
	0xf7, 0x0c, 0x25, 0x1b, 0xdf, 0xc0, 0xd2, 0x08, 0xd9, 0xa9, 0x41, 0xe9, 0x0a, 0xf7, 0x95, 0xe7,
	0xfc, 0xa7, 0xb3, 0x0c, 0x73, 0x3d, 0x14, 0xe7, 0x58, 0x79, 0x2e, 0x0f, 0x5f, 0xcd, 0x7c, 0x69,
	0xb9, 0x6f, 0x2c, 0x28, 0x1f, 0xb7, 0xde, 0x11, 0x77, 0x15, 0x66, 0xc2, 0x96, 0x92, 0x9d, 0x09,
	0x5b, 0x83, 0x3c, 0x94, 0x8c, 0x3c, 0x3c, 0x9b, 0x10, 0xda, 0xa7, 0x13, 0x42, 0x33, 0x8d, 0xfd,
	0x3f, 0x03, 0xfb, 0xab, 0x05, 0xf6, 0xd0, 0x12, 0x75, 0x9e, 0x42, 0x8d, 0xfb, 0xe9, 0x67, 0x43,
	0xac, 0x69, 0x09, 0x2f, 0x77, 0xde, 0x79, 0x01, 0xde, 0x52, 0x5e, 0x38, 0x53, 0xe7, 0x14, 0xaa,
	0x61, 0xab, 0xa0, 0x4b, 0xbe, 0xa0, 0xad, 0x77, 0x44, 0xec, 0x55, 0x42, 0xe3, 0x44, 0xdd, 0xaf,
	0xc1, 0x3e, 0x8c, 0xb3, 0xf3, 0x94, 0xca, 0x47, 0x5c, 0x83, 0x52, 0x1e, 0x85, 0x22, 0xc0, 0x8a,
	0xc7, 0x7f, 0x3a, 0x1b, 0xb0, 0x90, 0x29, 0xaa, 0x8a, 0x71, 0x70, 0x76, 0x3f, 0x01, 0xfb, 0x3c,
	0x4a, 0xda, 0x1e, 0x7e, 0x9d, 0x63, 0xca, 0xf8, 0x3b, 0xcc, 0x50, 0x3f, 0x4e, 0x51, 0xa8, 0x32,
	0xa4, 0x8f, 0xee, 0x2e, 0x94, 0x25, 0x23, 0xcd, 0xd2, 0x84, 0xe2, 0xb7, 0x70, 0x3e, 0x84, 0xf2,
	0x45, 0x8c, 0x71, 0xa6, 0x75, 0x6e, 0xc0, 0x42, 0x98, 0x13, 0xd1, 0x6b, 0x05, 0x6b, 0xc9, 0x1b,
	0x9c, 0xdd, 0x25, 0xa8, 0x28, 0x5e, 0xa9, 0xd6, 0xfd, 0x97, 0x05, 0xce, 0xc9, 0x0d, 0x0e, 0x72,
	0x86, 0x9f, 0xa4, 0xe9, 0x95, 0xd6, 0x31, 0xa9, 0xed, 0x6e, 0x02, 0x64, 0x88, 0xa0, 0x2e, 0x66,
	0x98, 0xc8, 0xdc, 0x2d, 0x7a, 0x06, 0xe2, 0x9c, 0xc3, 0x22, 0xbe, 0x61, 0x04, 0xf9, 0x38, 0xe9,
	0x89, 0x06, 0x6c, 0xef, 0x7f, 0x36, 0x21, 0xb5, 0xe3, 0xd6, 0xf6, 0x4e, 0xb8, 0xd8, 0x49, 0xd2,
	0x93, 0x05, 0xb5, 0x80, 0xd5, 0x71, 0xe3, 0x6b, 0xa8, 0x14, 0x48, 0x77, 0x2a, 0xa6, 0x4b, 0x68,
	0x14, 0x4c, 0xa9, 0x3c, 0x6e, 0x81, 0x8d, 0x6f, 0x22, 0xe6, 0x53, 0x86, 0x58, 0x4e, 0x55, 0x82,
	0x80, 0x43, 0x17, 0x02, 0x11, 0xd3, 0x85, 0x85, 0x69, 0xce, 0x06, 0xd3, 0x45, 0x9c, 0x14, 0x8e,
	0x89, 0x7e, 0x42, 0xea, 0xe4, 0xf6, 0xa0, 0xf6, 0x18, 0x33, 0xd9, 0x94, 0x74, 0xfa, 0x56, 0x61,
	0x5e, 0x04, 0x2e, 0xcb, 0x75, 0xd1, 0x53, 0x27, 0xe7, 0x3e, 0x54, 0xa2, 0x24, 0x88, 0xf3, 0x10,
	0xfb, 0xbd, 0x08, 0x5f, 0x53, 0x61, 0x62, 0xc1, 0x2b, 0x2b, 0xf0, 0x25, 0xc7, 0x9c, 0x8f, 0xa1,
	0x8a, 0x6f, 0x24, 0x93, 0x52, 0x22, 0xa7, 0x59, 0x45, 0xa1, 0xa2, 0xbb, 0x53, 0x17, 0x43, 0xdd,
	0xb0, 0xab, 0xa2, 0x3b, 0x87, 0xba, 0x6c, 0xab, 0xc6, 0xa4, 0xb8, 0x4b, 0xab, 0xae, 0xd1, 0x11,
	0xc4, 0x5d, 0x83, 0x95, 0xc7, 0x98, 0x19, 0xf5, 0xaf, 0x62, 0x74, 0xff, 0x00, 0xab, 0xa3, 0x04,
	0xe5, 0xc4, 0xef, 0xc0, 0x2e, 0xbe, 0x58, 0x6e, 0x7e, 0x73, 0x82, 0x79, 0x53, 0xd8, 0x14, 0x71,
	0x97, 0xc1, 0xb9, 0xc0, 0xcc, 0xc3, 0x28, 0x7c, 0x96, 0xc4, 0x7d, 0x6d, 0x71, 0x05, 0x1a, 0x05,
	0x54, 0x95, 0xf0, 0x10, 0x7e, 0x45, 0x22, 0x86, 0x35, 0xf7, 0x2a, 0x2c, 0x17, 0x61, 0xc5, 0xfe,
	0x2d, 0xd4, 0xe5, 0x64, 0x7b, 0xde, 0xcf, 0x34, 0xb3, 0xf3, 0x1b, 0xb0, 0xa5, 0x7b, 0xbe, 0x98,
	0xfb, 0xdc, 0xe5, 0xea, 0xfe, 0xf2, 0xde, 0x60, 0x8d, 0x11, 0x39, 0x67, 0x42, 0x02, 0xd8, 0xe0,
	0x37, 0xf7, 0xd3, 0xd4, 0x35, 0x74, 0xc8, 0xc3, 0x97, 0x04, 0xd3, 0x0e, 0x2f, 0x29, 0xd3, 0xa1,
	0x22, 0xac, 0xd8, 0xd7, 0x60, 0xc5, 0xcb, 0x93, 0x27, 0x18, 0xc5, 0xac, 0x23, 0xa6, 0x8e, 0x16,
	0x68, 0xc2, 0xea, 0x28, 0x41, 0x89, 0x7c, 0x0e, 0xcd, 0xb3, 0x76, 0x92, 0x12, 0x2c, 0x89, 0x27,
	0x84, 0xa4, 0xa4, 0xd0, 0x52, 0x18, 0xc3, 0x24, 0x19, 0x36, 0x0a, 0x71, 0x74, 0x3f, 0x82, 0xf5,
	0x09, 0x52, 0x4a, 0xe5, 0x57, 0xdc, 0x69, 0xde, 0x4f, 0x8a, 0x95, 0x7c, 0x1f, 0x2a, 0xd7, 0x28,
	0x62, 0xfe, 0xa0, 0xa1, 0x49, 0x9d, 0x65, 0x0e, 0xea, 0x16, 0x28, 0x23, 0x33, 0x65, 0x95, 0xce,
	0x7d, 0x58, 0x3d, 0x27, 0xf8, 0x32, 0x8e, 0xda, 0x9d, 0x91, 0x07, 0xc2, 0x57, 0x35, 0x91, 0x38,
	0xfd, 0x42, 0xf4, 0xd1, 0x6d, 0xc3, 0xda, 0x98, 0x8c, 0xaa, 0xab, 0xa7, 0x50, 0x95, 0x5c, 0x3e,
	0x11, 0x4b, 0x89, 0x1e, 0x06, 0x1f, 0xdf, 0x5a, 0xd9, 0xe6, 0x0a, 0xe3, 0x55, 0x02, 0xe3, 0x44,
	0xdd, 0xff, 0x5a, 0xe0, 0x1c, 0x64, 0x59, 0xdc, 0x2f, 0x7a, 0x56, 0x83, 0x12, 0x7d, 0x1d, 0xeb,
	0x16, 0x43, 0x5f, 0xc7, 0xbc, 0xc5, 0x5c, 0xa6, 0x24, 0xc0, 0xea, 0xb1, 0xca, 0x03, 0xdf, 0x21,
	0x50, 0x1c, 0xa7, 0xd7, 0xbe, 0xb1, 0xda, 0x8a, 0xce, 0xb0, 0xe0, 0xd5, 0x04, 0xc1, 0x1b, 0xe2,
	0xe3, 0xdb, 0xd3, 0xec, 0x87, 0xda, 0x9e, 0xe6, 0xde, 0x73, 0x7b, 0xfa, 0xbb, 0x05, 0x8d, 0x42,
	0xf4, 0x2a, 0xc7, 0x3f, 0xbd, 0x3d, 0xef, 0x9f, 0x16, 0x34, 0x55, 0x23, 0x3f, 0xc5, 0x2c, 0xe8,
	0x1c, 0xd0, 0xe3, 0xd6, 0xe0, 0xb6, 0x96, 0x61, 0x4e, 0x7c, 0x77, 0x08, 0x37, 0xcb, 0x9e, 0x3c,
	0x38, 0x6b, 0x70, 0x2f, 0x6c, 0xf9, 0x62, 0x80, 0xa9, 0x1e, 0x1e, 0xb6, 0x7e, 0xe0, 0x23, 0x6c,
	0x1d, 0x16, 0xba, 0xe8, 0xc6, 0x27, 0xe9, 0x35, 0x55, 0xfb, 0xde, 0xbd, 0x2e, 0xba, 0xf1, 0xd2,
	0x6b, 0x2a, 0x76, 0xf1, 0x88, 0x8a, 0x25, 0xbb, 0x15, 0x25, 0x71, 0xda, 0xa6, 0xe2, 0x92, 0x16,
	0xbc, 0xaa, 0x82, 0x0f, 0x25, 0xca, 0x5f, 0x04, 0x11, 0xc5, 0x6e, 0x5e, 0xc1, 0x82, 0x57, 0x26,
	0xc6, 0x0b, 0x70, 0x1f, 0xc3, 0xfa, 0x04, 0x9f, 0x55, 0x8e, 0x1f, 0xc2, 0xbc, 0x2c, 0x60, 0x95,
	0x5c, 0x67, 0x4f, 0x7e, 0x3b, 0xfd, 0xc8, 0xff, 0xaa, 0x62, 0x55, 0x1c, 0xee, 0x9f, 0x2c, 0xf8,
	0x59, 0x51, 0xd3, 0x41, 0x1c, 0xf3, 0x1d, 0x8b, 0x7e, 0xf8, 0x14, 0x8c, 0x45, 0x36, 0x3b, 0x21,
	0xb2, 0xa7, 0xb0, 0x79, 0x9b, 0x3f, 0xef, 0x11, 0xde, 0x77, 0xa3, 0x77, 0x7b, 0x90, 0x65, 0x6f,
	0x0f, 0xcc, 0xf4, 0x7f, 0xa6, 0xe0, 0xff, 0x78, 0xd2, 0x85, 0xb2, 0xf7, 0xf0, 0x8a, 0x8f, 0x9f,
	0x18, 0xf5, 0xb0, 0xdc, 0x08, 0x74, 0x3b, 0x3e, 0x85, 0x46, 0x01, 0x55, 0x8a, 0x3f, 0xe5, 0x7b,
	0xc1, 0x60, 0x97, 0xb0, 0xf7, 0xd7, 0xf6, 0x46, 0x3f, 0x76, 0x95, 0x80, 0x62, 0xe3, 0xfd, 0xfe,
	0x7b, 0x44, 0x19, 0x26, 0xba, 0x7f, 0x6a, 0x03, 0x9f, 0xc3, 0xea, 0x28, 0x41, 0xd9, 0x30, 0x37,
	0x4a, 0x6b, 0x64, 0xa3, 0x74, 0xa0, 0x76, 0xc1, 0xd2, 0x4c, 0xb8, 0xa6, 0x35, 0x35, 0xa0, 0x6e,
	0x60, 0xaa, 0x1b, 0xff, 0x1e, 0xd6, 0x06, 0xe0, 0xf7, 0x51, 0x12, 0x75, 0xf3, 0xae, 0xb1, 0x32,
	0xde, 0xa6, 0xdf, 0xd9, 0x01, 0xd1, 0xec, 0x7d, 0x16, 0x75, 0xb1, 0xde, 0x8a, 0x4a, 0x9e, 0xcd,
	0xb1, 0xe7, 0x12, 0x72, 0xbf, 0x80, 0xe6, 0xb8, 0xe6, 0x29, 0x5c, 0x17, 0x6e, 0x22, 0xc2, 0x0a,
	0xbe, 0xf3, 0xe4, 0x1b, 0xa0, 0x72, 0xfe, 0x18, 0x76, 0xe4, 0x0c, 0x3e, 0xb9, 0xe1, 0xb3, 0x0c,
	0xc5, 0x7c, 0x01, 0xc8, 0x10, 0xc1, 0x09, 0xc3, 0xa1, 0x0e, 0x43, 0xec, 0x76, 0x92, 0xec, 0x47,
	0x7a, 0x4f, 0x06, 0x0d, 0x9d, 0x85, 0xee, 0x03, 0x70, 0xdf, 0xa6, 0x45, 0xd9, 0xda, 0x86, 0xcd,
	0x51, 0xae, 0x93, 0x18, 0x07, 0x43, 0x43, 0xee, 0x0e, 0x6c, 0xdd, 0xca, 0xa1, 0x94, 0x38, 0x72,
	0x2d, 0xe4, 0x41, 0x0c, 0x2a, 0xe8, 0x17, 0x72, 0x65, 0x53, 0x98, 0x4a, 0xd0, 0x32, 0xcc, 0xa1,
	0x30, 0x24, 0x7a, 0x10, 0xca, 0x83, 0xfb, 0x47, 0x58, 0x7d, 0x85, 0x22, 0x66, 0x7c, 0x68, 0xe8,
	0x20, 0x0f, 0xa0, 0xdc, 0x8a, 0xb3, 0xe2, 0x40, 0x9e, 0xbc, 0x5e, 0x99, 0xc2, 0x76, 0xcb, 0xf8,
	0x64, 0x99, 0xe2, 0x4a, 0xd7, 0x61, 0x6d, 0xcc, 0xbe, 0x8a, 0xac, 0x06, 0x55, 0x7e, 0xdb, 0x87,
	0xb1, 0x7e, 0xa9, 0xee, 0x4b, 0x58, 0x1a, 0x20, 0x2a, 0xaa, 0x23, 0xa8, 0x98, 0x5e, 0xea, 0x51,
	0xfd, 0x2e, 0x37, 0xcb, 0x86, 0x9b, 0xd4, 0xad, 0x73, 0xbd, 0x88, 0x30, 0xc3, 0x94, 0xa8, 0x76,
	0x0d, 0x29, 0x87, 0xfe, 0x61, 0x81, 0xe3, 0xe5, 0xc9, 0x61, 0x9c, 0xbd, 0x48, 0x58, 0x14, 0xeb,
	0x44, 0x7d, 0x08, 0x17, 0xa6, 0x48, 0x95, 0xf3, 0x10, 0xea, 0x91, 0x58, 0xab, 0x7c, 0x8a, 0x49,
	0x0f, 0x13, 0x3f, 0x0a, 0xa9, 0xfa, 0x46, 0x58, 0x92, 0x84, 0x0b, 0x81, 0x9f, 0x85, 0xd4, 0x7d,
	0x04, 0x8d, 0x82, 0xa7, 0x53, 0x3c, 0x92, 0x75, 0x58, 0xf3, 0x30, 0xe5, 0x9b, 0xec, 0xa0, 0xab,
	0xe8, 0x64, 0x6c, 0x40, 0x73, 0x9c, 0xa4, 0x92, 0xd2, 0x80, 0xfa, 0x59, 0x12, 0x31, 0xd9, 0x50,
	0xb4, 0xc0, 0xaf, 0xc1, 0x31, 0xc1, 0x29, 0xac, 0xbf, 0xb1, 0x60, 0xf3, 0x3c, 0xcd, 0xf2, 0x58,
	0x6c, 0xac, 0xf2, 0xa9, 0x7c, 0x9b, 0xe6, 0xbc, 0xe6, 0x75, 0x9e, 0x7f, 0x0e, 0x4b, 0x3c, 0x3b,
	0x7e, 0x40, 0x30, 0x62, 0x38, 0xf4, 0x13, 0xfd, 0x55, 0x55, 0xe1, 0xf0, 0x91, 0x44, 0x7f, 0xa0,
	0xfc, 0x75, 0xa2, 0x80, 0x2b, 0x35, 0xc7, 0x12, 0x48, 0x48, 0x8c, 0xa6, 0x2f, 0xa1, 0xdc, 0x15,
	0x9e, 0xf9, 0x28, 0x8e, 0x90, 0xcc, 0xa1, 0xbd, 0xbf, 0x32, 0xba, 0x85, 0x1f, 0x70, 0xa2, 0x67,
	0x4b, 0x56, 0x71, 0x70, 0x1e, 0xc1, 0xb2, 0xd1, 0x74, 0x87, 0x6f, 0x63, 0x56, 0xd8, 0x68, 0x18,
	0xb4, 0xc1, 0xce, 0xba, 0x03, 0x5b, 0xb7, 0xc6, 0xa5, 0x52, 0xf8, 0x17, 0x0b, 0x6a, 0x3c, 0x5d,
	0x66, 0x7b, 0x72, 0x7e, 0x05, 0xf3, 0x92, 0x5b, 0x3d, 0xbc, 0x5b, 0xdc, 0x53, 0x4c, 0xb7, 0x7a,
	0x36, 0x73, 0xab, 0x67, 0x93, 0xf2, 0x59, 0x9a, 0x90, 0x4f, 0x7d, 0xc3, 0xc5, 0x3e, 0xb9, 0x02,
	0x8d, 0x63, 0xdc, 0x4d, 0x19, 0x2e, 0x5e, 0xfc, 0x3e, 0x2c, 0x17, 0xe1, 0x29, 0xae, 0xfe, 0x1b,
	0xd8, 0x3a, 0x27, 0x29, 0x17, 0x12, 0x26, 0x5e, 0x75, 0x70, 0x72, 0x84, 0xf2, 0x76, 0x87, 0xbd,
	0xc8, 0xa6, 0x98, 0x1b, 0xee, 0x6f, 0x61, 0xfb, 0x76, 0xf1, 0xe9, 0xea, 0x5e, 0x0a, 0x22, 0xaa,
	0xf4, 0x84, 0x46, 0xdd, 0x8f, 0x93, 0x54, 0x02, 0xfe, 0x6c, 0x41, 0xed, 0x02, 0x17, 0xeb, 0xfe,
	0xae, 0x97, 0x36, 0xe1, 0x06, 0x66, 0x26, 0x55, 0xf4, 0x43, 0xa8, 0x8b, 0x8f, 0x01, 0x9f, 0xf2,
	0x96, 0xe4, 0x53, 0xee, 0x93, 0xfa, 0x06, 0x58, 0x12, 0x84, 0xe1, 0x20, 0x13, 0xb3, 0x0e, 0x8f,
	0xbc, 0x3c, 0xf7, 0x6c, 0x18, 0x88, 0x87, 0x85, 0x92, 0xe1, 0x30, 0xbb, 0x9b, 0xcf, 0xfc, 0xe3,
	0x6e, 0x82, 0x2a, 0x65, 0xe7, 0x01, 0xb8, 0xbc, 0x41, 0x1b, 0x7d, 0xe2, 0x20, 0x09, 0xf9, 0x28,
	0x2a, 0x2c, 0x38, 0x2f, 0xe1, 0xfe, 0x5b, 0xb9, 0xde, 0x77, 0xe1, 0x59, 0x81, 0x86, 0x59, 0x09,
	0x46, 0x4d, 0x16, 0xe1, 0x29, 0x8a, 0xe2, 0x11, 0x54, 0x0e, 0x51, 0x70, 0x95, 0x0f, 0x2a, 0x70,
	0x1b, 0xec, 0x20, 0x4d, 0x82, 0x9c, 0x10, 0x9c, 0x04, 0x7d, 0xd5, 0x78, 0x4c, 0xc8, 0xfd, 0x02,
	0xaa, 0x5a, 0x44, 0x19, 0x78, 0x00, 0x73, 0xb8, 0x37, 0x4c, 0x6c, 0x75, 0x4f, 0xff, 0x1b, 0xe2,
	0x84, 0xa3, 0x9e, 0x24, 0xaa, 0xe6, 0xca, 0x52, 0x82, 0x4f, 0x49, 0xda, 0x2d, 0x58, 0x75, 0x0f,
	0x60, 0x7d, 0x02, 0xed, 0x2e, 0xea, 0x5b, 0xf3, 0xe2, 0x7f, 0x1e, 0x9f, 0xfd, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x45, 0xda, 0xb6, 0x64, 0x19, 0x00, 0x00,
}
